Fix #44
naruhiyo/aman pull request #45
Opened 2020-12-27 09:53 UTC by narugit

### 先行PR
- #40
- #41 
- #43 

### 内容
#44 の修正

### 動作確認項目
`bash`、`zsh`上で下記コマンドで実行時エラーが発生した後も
- ctrl+cによるSIGINTが有効
- エコーバックされる

ことを確認
```console
$ go run main.go aman
```

- bashバージョン：3.2.57
- zshバージョン：5.8

### 備考
無し

2020-12-28 03:36 UTC, hiyoko3 requested changes

2020-12-28 03:36 UTC, hiyoko3 commented on main.go
> +	defer func() {
ここはコード自体問題ないので、外だしできますか？

main 内はメソッドへの命令だけを行うという感じにしたいので

2020-12-29 03:24 UTC, narugit commented on main.go
> +	defer func() {
471c13d にて対応しました。

2020-12-29 07:57 UTC, hiyoko3 approved these changes

2020-12-29 08:00 UTC, merged