Fix #47, #49
naruhiyo/aman pull request #50
Opened 2020-12-28 10:54 UTC by hiyoko3

### 内容
Fix
- #47 
- #49 

### 動作確認項目
<img width="697" alt="スクリーンショット 2020-12-28 19 53 52" src="https://user-images.githubusercontent.com/16721102/103209431-6f5f7f80-4946-11eb-9536-54adb6468b19.png">

### 備考

2020-12-29 03:41 UTC, narugit requested changes
対応ありがとうございます。

2020-12-29 03:41 UTC, narugit commented on .gitignore
> +dist
最後に空行お願いします。

2020-12-29 03:41 UTC, narugit commented on implement/io/input.go
> +
データなので、`struct/io`が管理した方が良いと思います。

2020-12-29 03:41 UTC, narugit commented on implement/io/input.go
> +		fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
この次の行あたりで、`aman ls`や`aman git`や`aman git status`のように使うという使用例の記載があると良いと思います。

2020-12-29 03:41 UTC, narugit commented on implement/io/input.go
> +	versionFlag = flag.Bool("v", false, "show version")
`-h`オプションの説明も追加お願いします。

2020-12-29 03:42 UTC, narugit commented on implement/io/input.go
> +
データなので、`struct/io`が管理した方が良いと思います。

2020-12-29 08:20 UTC, hiyoko3 commented
`--help` はgo の flag パッケージで勝手にセットされるらしく、対応に時間がかかりそう（できないことはないけど）
ヘルプで `--help` を記載しないことで対応できるのではないかと考えていますが、どうでしょうか？

<img width="722" alt="スクリーンショット 2020-12-29 17 17 36" src="https://user-images.githubusercontent.com/16721102/103269820-ee61c000-49f9-11eb-85de-2e57df0271be.png">

2020-12-29 08:37 UTC, narugit requested changes

2020-12-29 08:37 UTC, narugit commented on .gitignore
> +dist
ここ確認お願いします。

2020-12-29 08:37 UTC, narugit commented on implement/io/input.go
> +		"  - Output the integrated commands to your console\n"
`$ go --help`とか`$ git --help`を参考に、実用例メインで記載する下記形式はどうでしょう？

```suggestion
	usageText  = "usage: aman <command> [arguments]\n" 
		"  <command>: command which has man result (ls, git,...)\n" +
		" [arguments]: arguments which command have ("status" for "git status")
```

2020-12-29 08:44 UTC, narugit commented
> `--help` はgo の flag パッケージで勝手にセットされるらしく、対応に時間がかかりそう（できないことはないけど）
> ヘルプで `--help` を記載しないことで対応できるのではないかと考えていますが、どうでしょうか？
> 
> <img alt="スクリーンショット 2020-12-29 17 17 36" width="722" src="https://user-images.githubusercontent.com/16721102/103269820-ee61c000-49f9-11eb-85de-2e57df0271be.png">

https://github.com/jessevdk/go-flags

これ使えば、オプションのlong nameとshort nameを定義できそうでしょうか？

2020-12-30 02:04 UTC, hiyoko3 commented
<img width="744" alt="スクリーンショット 2020-12-30 11 03 25" src="https://user-images.githubusercontent.com/16721102/103325354-d25c2e00-4a8e-11eb-8657-e9ae07d79ba9.png">

2020-12-30 04:51 UTC, narugit approved these changes

2020-12-30 06:36 UTC, merged